// resourceConfig.ts

export const resources = {
    METAL_QUANTITY: 10,
    WATER_QUANTITY: 10,
    ORGANIC_MATERIAL_QUANTITY: 10,
    OXYGEN_QUANTITY: 10,
    CRYSTAL_QUANTITY: 10,
    ENERGY_FRAGMENT_QUANTITY: 10,
    STONE_QUANTITY: 10,
    NANO_MATERIALS_QUANTITY: 10,
    HYDROGEN_QUANTITY: 10,
    RADIOACTIVE_MATERIALS_QUANTITY: 10,

    METAL_TOKEN_ADDRESS: 'BjmxM9zz2YVQMadUyQoLdAd5fRv3fzTLS6R6TerBzWiN',
    WATER_TOKEN_ADDRESS: 'EArDdP8y7bzbF5PYjM8f6cGbtDA7BPaKwUsD1q8UmArK',
    STONE_TOKEN_ADDRESS: '7mtdsz47ssQQ4fHPYh91NgyBbcnJsShw9mNbro5NKf1f',
    CRYSTAL_TOKEN_ADDRESS: 'GSWjDToPkQT43xy5uwwZt4mushLQeoBC2fjsb1L3FbNr',
    ENERGY_FRAGMENT_TOKEN_ADDRESS: 'CLNX8gTNWFrhVPT5ED39YKgHsfPC8qitxgxqBQKiZ38k',
    NANO_MATERIALS_TOKEN_ADDRESS: 'CjeGjYdCu4ccwdtaGXbbxeHsN6UV5CUr8RYEubpbvH19',
    HYDROGEN_TOKEN_ADDRESS: 'nf86v1TyJpPpKiRJCGV3ZGVvteLpMzo69tbNnJeFvsX',
    OXYGEN_TOKEN_ADDRESS: '7Hp7cjauvXDUQfHCbwLpazHLWMU2VuNS2W8tC1ifq6r6',
    RADIOACTIVE_TOKEN_ADDRESS: 'BjmxM9zz2YVQMadUyQoLdAd5fRv3fzTLS6R6TerBzWiN',
    ORGANIC_MATERIAL_TOKEN_ADDRESS: 'F25sjygRH75QjA8J1A8HvRPQeuD2QNhGB4FbjG3pJCar',
};
